Updating guide’s content to use the Liberty AKS portal for creating cluster, resource group, and container
OpenLiberty/guide-cloud-azure pull request #129
Opened 2024-07-22 20:45 UTC by Ruilin-Ma

2024-08-02 21:45 UTC, gkwan-ibm commented on README.adoc
> +This guide will introduce **IBM WebSphere Liberty and Open Liberty on AKS**, which solution automates the majority of standard steps involved in provisioning WebSphere Liberty or Open Liberty on an A
Is it better to change **IBM WebSphere Liberty and Open Liberty on AKS** to [WebSphere Liberty/Open Liberty on Kubernetes](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/ibm-usa-ny-armonk-hq-6275750-ibmcloud-aiops.20210924-liberty-aks?tab=Overview)

2024-08-02 21:49 UTC, gkwan-ibm commented on README.adoc
> +* *IBM WebSphere Liberty and Open Liberty on AKS:* You will need to use the IBM WebSphere Liberty and Open Liberty on AKS on Azure marketplace. See the official
Is "WebSphere Liberty/Open Liberty on Kubernetes" the official name instead of "IBM WebSphere Liberty and Open Liberty on AKS"?

2024-08-02 21:53 UTC, gkwan-ibm commented on README.adoc
> +== Provision deployment foundation with IBM Liberty on AKS
"IBM Liberty" -> "Liberty"

2024-08-02 22:12 UTC, gkwan-ibm commented on README.adoc
> +To create the resource group in an efficient way, check out the https://aka.ms/liberty-aks[IBM Liberty on AKS] tool and click on the `Create` button to start the process.
"...[IBM Liberty on AKS] tool ..." -> "...[IBM WebSphere Liberty and Open Liberty on AKS] plan..."

2024-08-02 22:16 UTC, gkwan-ibm commented on README.adoc
> +On the `Basics` pane. Under the `Resource group`, select `Create new` and type in **guideGroup** as the name of the resource group. Please note, the offer also supports to use an existing resource gr
- "...select `Create new`..." -> "...click on the `Create new` link ..."
- **guideGroup** -> `guideGroup`

2024-08-02 22:18 UTC, gkwan-ibm commented on README.adoc
> +An Azure location must be specified. The metadata for your resources are stored at this specified Azure location. If resources are created later without specifying a location, these new resources wil
- insert a screenshot for the Region selection

2024-08-08 16:20 UTC, gkwan-ibm commented on README.adoc
insert a screenshot for the Region selection

2024-08-08 16:20 UTC, gkwan-ibm commented on README.adoc
> +image::Locate_ACR.png[Locate ACR,align="center"]
- can make the text bigger in this screenshot?

2024-08-08 18:30 UTC, gkwan-ibm commented
- search the role requirement from azure doc for users to create resource group, then add those prereq in the content

2024-08-09 13:15 UTC, gkwan-ibm commented
- [x] It is better to simplify the content of the **Provision deployment foundation with Liberty on AKS** section. The guide has no need to describe in detail like as a doc. Users only need to provide info in the Basics pane and leave other panes as default. After filling up the Basics pane, they can click the **Review+Create** button to create the resources group and cluster. Let the guide to demonstrate how simple to create them. Just mention that if interest to know more configuration, they can visit the other panes.
- [x] in the **Access the created cluster** section, is there a command, e.g. `az aks show`, to get the `[cluster-name]` instead of from the GUI?
- [x] `clusterXXXXXX` in the output can be replaced by a makeup string, e.g. `cluster1234d5`
- [x] in the **Logging into the container registry** subsection, can add a command to get the `[registry-name]`? In this case, screenshot can be kept.

2024-08-13 18:47 UTC, gkwan-ibm commented
- [ ] remove
  - > Please note, the plan also supports to use an existing resource group while the group is required to be empty. 
- [ ] Before this statement "To push Docker images to your registry, you must log in to your Azure Container Registry by using the Azure CLI.", need to tell users which value is the `[registry-name]`, e.g. acr1234d5 under the `NAME` column from the output

2024-09-24 17:50 UTC, shin19991207 commented
Address Laura's comments:
- [x] Can you remove the bold highlighting on the names in the What you’ll learn and the Additional prereqs sections, pls? It’s not necessary.
- [x] “a cost may associated” > “a cost may be associated”
- [x] “Azure Subscription:” should be “Azure subscription:“.
- [x] “IBM WebSphere Liberty and Open Liberty on AKS:” should be “IBM WebSphere Liberty and Open Liberty on AKS plan:” But also remove all the bold highlighting here.
- [ ] “Provision deployment foundation with Liberty on AKS” and others sections need to have some kind of introduction for the section before the first sub-heading (see old Azure guide for example, though it too doesn’t always do it but should).
- [ ] Not sure about the heading “Provision deployment foundation with Liberty on AKS” - could do with something more meaningful I think.

2024-10-04 15:29 UTC, gkwan-ibm commented
- [ ] Somewhere need to mention the plan/provisioning of the cluster also provides the OL operator.
- [ ] test on Win
- [ ] on Mac, the `az aks install-cli` command need to use `sudo az aks install-cli`. Linix may need `sudo` too. Surely it may different than Win.
- ... dev review not complete yet

2024-10-06 12:27 UTC, shin19991207 commented
> - [x] on Mac, the `az aks install-cli` command need to use `sudo az aks install-cli`. Linix may need `sudo` too. Surely it may different than Win.

- [Sudo for Windows](https://learn.microsoft.com/en-us/windows/sudo/) requires Windows 11 Insider Preview Build 26052 or higher
- [Runas](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc771525(v=ws.11))
  - The `runas` command in Windows requires running with a full path, i.e. `runas /user:Administrator "C:\path\to\az.cmd aks install-cli"`
  - Every Windows installation has a built-in Administrator account. However, it is not always enabled by default.
  - Alternatively, instead of using `runas`, you can open Command Prompt or PowerShell as Administrator (right-click > "Run as administrator") and then run the command(s)

2025-01-30 20:20 UTC, dmuelle requested changes
ID review- let me now if you have any questions. Thanks

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +Kubernetes is an open source container orchestrator that automates many tasks involved in deploying, managing, and scaling containerized applications. If you would like to learn more about Kubernetes
```suggestion
Kubernetes is an open source container orchestrator that automates many tasks involved in deploying, managing, and scaling containerized applications. To learn more about Kubernetes and how to use it with the Open Liberty Operator, check out the https://openliberty.io/guides/openliberty-operator-intro.html[Deploying a microservice to Kubernetes using Open Liberty Operator^] guide.
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +Azure offers a managed {kube} service called Azure Kubernetes Service (AKS). Using AKS simplifies the process of running Kubernetes on Azure without needing to install or maintain your own Kubernetes
```suggestion
Azure offers a managed {kube} service called Azure Kubernetes Service (AKS). Using AKS simplifies the process of running Kubernetes on Azure without needing to install or maintain your own Kubernetes control plane. It provides a hosted {kube} cluster that you can deploy your microservices to. You will use AKS with Azure Container Registry (ACR). ACR is a private registry that is used to store and distribute your container images. Because AKS is not free, a cost might be associated with running this guide. See the official https://azure.microsoft.com/en-us/pricing/details/kubernetes-service/[AKS pricing^] documentation for more details.
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +This guide will introduce IBM WebSphere Liberty and Open Liberty on AKS plan, a solution that automates most of the standard steps for provisioning WebSphere Liberty or Open Liberty on an AKS cluster
```suggestion
This guide will introduce the IBM WebSphere Liberty and Open Liberty on AKS plan, a solution that automates most of the standard steps for provisioning WebSphere Liberty or Open Liberty on an AKS cluster. Once the initial provisioning is complete, you can further customize your deployments as needed.
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +* *Azure subscription:* To run this guide, you will need an Azure subscription. Navigate to the
```suggestion
* *Azure subscription*: To run this guide, you will need an Azure subscription. Navigate to the 
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +* *IBM WebSphere Liberty and Open Liberty on AKS plan:* You will need to use the IBM WebSphere Liberty and Open Liberty on AKS plan on Azure marketplace. See the official
```suggestion
* *IBM WebSphere Liberty and Open Liberty on AKS plan*: You will need to use the IBM WebSphere Liberty and Open Liberty on AKS plan on Azure marketplace. See the official
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
>  * *kubectl:* You need the Kubernetes command-line tool `kubectl` to interact with your Kubernetes cluster.
```suggestion
* *kubectl*: You need the Kubernetes command-line tool `kubectl` to interact with your Kubernetes cluster.
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +A resource group is an Azure construct to manage a logical collection of resources for your cloud deployments on Azure. You must create a new resource group to hold and manage the resources you need
```suggestion
A resource group is an Azure construct to manage a logical collection of resources for your cloud deployments on Azure. You must create a resource group to hold and manage the resources you need for your Kubernetes deployment.
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +After setting up the resource group, you can leave the remaining configuration at its default settings by skipping the **AKS**, **Load balancing**, and **Operator and application** panes. The default
```suggestion
After you set up the resource group, leave the remaining configuration at its default settings by skipping the **AKS**, **Load balancing**, and **Operator and application** panes. The default configuration automatically sets up an https://azure.microsoft.com/en-ca/products/container-registry[Azure Container Registry^] in the same region where your services are deployed, links it to your resource group, creatse an https://learn.microsoft.com/en-us/azure/aks/tutorial-kubernetes-deploy-cluster?tabs=azure-cli[AKS cluster^], and deploys the https://github.com/OpenLiberty/open-liberty-operator/releases/latest[Open Liberty Operator^] to manage your Open Liberty applications.
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +For more information on configuring these options, refer to the https://learn.microsoft.com/en-us/azure/aks/howto-deploy-java-liberty-app?tabs=in-bash#create-a-liberty-on-aks-deployment-using-the-por
```suggestion
For more information on configuring these options, see the https://learn.microsoft.com/en-us/azure/aks/howto-deploy-java-liberty-app?tabs=in-bash#create-a-liberty-on-aks-deployment-using-the-portal[Create a Liberty on AKS deployment using the portal] documentation.
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +Once you have reviewed the configurations, select **Review + create** to validate your setup. After validation, click **Create** to initiate the deployment, which can take up to 20 minutes to complet
```suggestion
After you review the configurations, select **Review + create** to validate your setup. After validation, click **Create** to initiate the deployment, which can take up to 20 minutes to complete. You'll see a `Deployment is in progress` message, and when the deployment is complete, a `Your deployment is complete` message will confirm the creation of the ACR and AKS cluster.
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +Once your Azure Container Registry (ACR) is created, you can proceed to containerize your microservices and upload their Docker images to the ACR for storage and deployment.
```suggestion
Once your Azure Container Registry (ACR) is created, you can containerize your microservices and upload their Docker images to the ACR for storage and deployment.
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +For example, in the figure below, the registry name is `acrc75e71`.
```suggestion
For example, in the following screenshot, the registry name is `acrc75e71`.
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +You will use this registry name in place of `[registry-name]` in the upcoming commands.
```suggestion
Use this registry name in place of `[registry-name]` in the upcoming commands.
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +This command will return a table with the details of your ACR, including its name. For example, you will see an output similar to the following:
```suggestion
This command returns a table with the details of your ACR, including its name. Look for output similar to the following example:
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +Your two images, `system` and `inventory`, should appear in the list of all Docker images:
```suggestion
Your two images, `system` and `inventory`, are included in the list of all Docker images:
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +First, retrieve your registry server name. This will typically be in the format `[registry-name].azurecr.io`. You can find this by running the following command:
```suggestion
First, retrieve your registry server name, which typically be in the following format: `[registry-name].azurecr.io`. You can find the server name by running the following command:
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +You will see an output similar to the following that will be used to substitute the `[registry-server]` value of the commands in below.
```suggestion
Look for output similar to the following example. 
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +Tag your container images with your registry by the following commands:
```suggestion
Tag your container images with your registry by the following commands. Substitute your registry server name for the `[registry-server]` value.
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +Finally, push your images to the registry by the following commands:
```suggestion
Finally, push your images to the registry by running the following commands:
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +To manage and interact with your AKS cluster using Kubernetes, you need to integrate the AKS cluster credentials into your local Kubernetes configuration. This allows your local Kubernetes CLI (`kube
```suggestion
To manage and interact with your AKS cluster using Kubernetes, you need to integrate the AKS cluster credentials into your local Kubernetes configuration. This integration allows your local Kubernetes CLI (`kubectl`) to communicate with the AKS cluster for deploying and managing resources.
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +To begin, obtain the information about the Kubernetes cluster created within the `guideGroup` resource group. You can do this by either viewing the resource group overview in the Azure Portal or exec
```suggestion
To begin, obtain the information about the Kubernetes cluster created within the `guideGroup` resource group. You can find this information by either viewing the resource group overview in the Azure Portal or running the following command:
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +The cluster name, formatted as `clusterXXXXXX`, should be identified in the following output.
```suggestion
The cluster name, formatted as `clusterXXXXXX`, is identified in the following output.
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +Merge the credentials of your cluster into your current Kubernetes configuration by using the `az aks get-credentials` command. Replacing `[cluster-name]` with the name of the cluster. The default Ku
```suggestion
Merge the credentials of your cluster into your current Kubernetes configuration by using the `az aks get-credentials` command. Replace `[cluster-name]` with the name of the cluster. The default Kubernetes configuration file that is updated with your cluster credentials is located within the `~/.kube/config` filepath.
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +The `kubectl get nodes` command outputs information about the node. Please ensure that the `STATUS` of the node is in the `Ready` state before proceeding with the subsequent steps.
```suggestion
The `kubectl get nodes` command outputs information about the node. Ensure that the `STATUS` of the node is in the `Ready` state before you proceed. 
```

2025-01-30 20:20 UTC, dmuelle commented on README.adoc
> +The Open Liberty Operator provides custom resource definitions (CRDs) that allow you to define how your Open Liberty applications are deployed. These CRDs are described in a `yaml` file, which outlin
```suggestion
The Open Liberty Operator provides custom resource definitions (CRDs) that define how your Open Liberty applications are deployed. These CRDs are described in a YAML file, which outlines the deployment details and services required for your application. You can also delete any resources from the cluster by using the same YAML file that you used to deploy them. In this guide, the [hotspot]`deploy.yaml` resource definition file is provided for you. To learn more about deploying microservices using the Open Liberty Operator, check out the https://openliberty.io/guides/openliberty-operator-intro.html[Deploying a microservice to Kubernetes using Open Liberty Operator^] guide.
```

2025-01-30 21:36 UTC, dmuelle approved these changes
ID LGTM, thanks

2025-01-31 16:05 UTC, gkwan-ibm approved these changes
verified end-to-end and had no issue

2025-01-31 19:13 UTC, yeekangc approved these changes
Thanks, everyone!  Let us proceed to publish.

2025-02-10 21:30 UTC, merged